[package]
name = "corkboard"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.9", package = "gtk4", features = ["v4_10"] }
libadwaita = { version = "0.7", features = ["v1_5"] }
sourceview5 = { version = "0.9", package = "sourceview5" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
